# Site Settings
title: Angel Fraga
tagline: Another Software Developer's Blog
description: >
  Another Software Developer's Blog
url: "https://angelfraga.com/"
permalink: pretty

lang: en

paginate: 6
paginate_path: "/blog/page:num"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - kramdown
  - rouge
  - github-pages
  - jekyll-redirect-from

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

markdown: kramdown
highlighter: rouge
