title: Angel Fraga
description: >-
  Another Software Developer's Blog
url: "https://angelfraga.com/"
github_username:  angelfraga

# Build settings
plugins:
  - jekyll-feed
theme: bulma-clean-theme
# global theme(bulma-clean-theme) settings
show_sidebar: true
menubar: navmenu
paginate: 5
paginate_path: "/blog/page:num"